import type { Product, Category, StockEntry, StockAlert } from "./types"

export const categories: Category[] = [
  {
    id: "sarees",
    name: "Sarees",
    description: "Exquisite collection of handwoven and designer sarees from across India",
    image: "/placeholder.svg?height=400&width=300&text=Elegant+Sarees",
    productCount: 150,
    featured: true,
    slug: "sarees",
    metaTitle: "Premium Sarees Collection - Traditional & Designer Sarees",
    metaDescription: "Discover beautiful handwoven sarees, silk sarees, cotton sarees and designer collections with authentic Indian craftsmanship.",
    displayOrder: 1,
    isActive: true,
  },
  {
    id: "lehengas",
    name: "Lehengas",
    description: "Stunning bridal and party wear lehengas with intricate embroidery",
    image: "/placeholder.svg?height=400&width=300&text=Designer+Lehengas",
    productCount: 85,
    featured: true,
    slug: "lehengas",
    metaTitle: "Designer Lehengas - Bridal & Party Wear Collection",
    metaDescription: "Shop stunning designer lehengas perfect for weddings, parties and special occasions. Premium quality with intricate embroidery work.",
    displayOrder: 2,
    isActive: true,
  },
  {
    id: "suits",
    name: "Suits & Sets",
    description: "Elegant salwar suits, sharara sets and coordinated ethnic wear",
    image: "/placeholder.svg?height=400&width=300&text=Elegant+Suits",
    productCount: 120,
    featured: true,
    slug: "suits-sets",
    metaTitle: "Salwar Suits & Ethnic Sets - Traditional Wear Collection",
    metaDescription: "Elegant salwar suits, sharara sets and coordinated ethnic wear for every occasion. Comfortable and stylish designs.",
    displayOrder: 3,
    isActive: true,
  },
  {
    id: "kurtis",
    name: "Kurtis",
    description: "Contemporary and traditional kurtis for modern women",
    image: "/placeholder.svg?height=400&width=300&text=Stylish+Kurtis",
    productCount: 95,
    featured: true,
    slug: "kurtis",
    metaTitle: "Designer Kurtis - Contemporary Indian Wear",
    metaDescription: "Stylish kurtis collection featuring contemporary and traditional designs perfect for office wear and casual occasions.",
    displayOrder: 4,
    isActive: true,
  },
]

export const featuredProducts: Product[] = [
  {
    id: "1",
    sku: "JL-BS-001",
    name: "Royal Banarasi Silk Saree",
    price: 12999,
    originalPrice: 15999,
    discount: 19,
    cost: 8500, // For profit margin calculation
    image: "/placeholder.svg?height=500&width=400&text=Banarasi+Silk+Saree",
    images: [
      "/placeholder.svg?height=500&width=400&text=Banarasi+Silk+Saree+1",
      "/placeholder.svg?height=500&width=400&text=Banarasi+Silk+Saree+2",
      "/placeholder.svg?height=500&width=400&text=Banarasi+Silk+Saree+3",
    ],
    category: "sarees",
    description: "Exquisite handwoven Banarasi silk saree with intricate gold zari work. Crafted by skilled artisans using traditional techniques passed down through generations. Perfect for weddings and special occasions.",
    colors: ["Deep Burgundy", "Golden", "Cream"],
    sizes: ["Free Size"],
    material: "Pure Silk",
    care: ["Dry clean only", "Store in cool, dry place", "Avoid direct sunlight"],
    features: ["Handwoven", "Pure Silk", "Gold Zari Work", "Traditional Design", "Heritage Craft"],
    rating: 4.8,
    reviews: 124,
    isNew: false,
    isBestseller: true,
    inStock: true,
    stockCount: 15,
    stockAlert: 5, // Alert when stock goes below 5
    vendor: "Banarasi Silk Weavers Co-op",
    weight: 0.8, // kg
    dimensions: { length: 6.5, width: 1.2, height: 0.1 }, // meters
    tags: ["handwoven", "silk", "traditional", "bridal", "festival"],
    condition: "new",
    warranty: "Authentic handloom guarantee",
    returnPolicy: "7 days return policy",
    lastRestocked: new Date("2024-01-15"),
  },
  {
    id: "2",
    sku: "JL-BL-002",
    name: "Designer Bridal Lehenga",
    price: 25999,
    originalPrice: 32999,
    discount: 21,
    cost: 18000,
    image: "/placeholder.svg?height=500&width=400&text=Bridal+Lehenga",
    images: [
      "/placeholder.svg?height=500&width=400&text=Bridal+Lehenga+1",
      "/placeholder.svg?height=500&width=400&text=Bridal+Lehenga+2",
      "/placeholder.svg?height=500&width=400&text=Bridal+Lehenga+3",
    ],
    category: "lehengas",
    description: "Stunning designer bridal lehenga with heavy embroidery and sequin work. Features intricate threadwork, pearl embellishments, and premium fabrics. Includes matching blouse and dupatta with delicate border work.",
    colors: ["Dusty Rose", "Gold Taupe", "Cream"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    material: "Silk & Net",
    care: ["Dry clean only", "Handle with care", "Store properly with tissue paper"],
    features: ["Heavy Embroidery", "Sequin Work", "3-Piece Set", "Bridal Collection", "Pearl Work"],
    rating: 4.9,
    reviews: 89,
    isNew: true,
    isBestseller: true,
    inStock: true,
    stockCount: 8,
    stockAlert: 3,
    vendor: "Luxury Bridal Studio",
    weight: 2.5,
    dimensions: { length: 4.0, width: 1.5, height: 0.2 },
    tags: ["bridal", "heavy-work", "designer", "wedding", "premium"],
    condition: "new",
    warranty: "Premium craftsmanship guarantee",
    returnPolicy: "10 days return with original tags",
    lastRestocked: new Date("2024-01-20"),
  },
  {
    id: "3",
    sku: "JL-AS-003",
    name: "Elegant Anarkali Suit",
    price: 8999,
    originalPrice: 11999,
    discount: 25,
    cost: 5500,
    image: "/placeholder.svg?height=500&width=400&text=Anarkali+Suit",
    images: [
      "/placeholder.svg?height=500&width=400&text=Anarkali+Suit+1",
      "/placeholder.svg?height=500&width=400&text=Anarkali+Suit+2",
    ],
    category: "suits",
    description: "Beautiful Anarkali suit with intricate embroidery and flowing silhouette. Features contemporary design with traditional elements, perfect for festive occasions and celebrations.",
    colors: ["Forest Green", "Burgundy", "Charcoal"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    material: "Georgette",
    care: ["Machine wash cold", "Do not bleach", "Iron on low heat"],
    features: ["Flowing Design", "Embroidered", "3-Piece Set", "Party Wear", "Contemporary Style"],
    rating: 4.6,
    reviews: 156,
    isNew: false,
    isBestseller: false,
    inStock: true,
    stockCount: 22,
    stockAlert: 8,
    vendor: "Modern Ethnic Designs",
    weight: 1.2,
    dimensions: { length: 3.5, width: 1.8, height: 0.15 },
    tags: ["anarkali", "party-wear", "embroidered", "georgette", "festive"],
    condition: "new",
    warranty: "Quality assurance guarantee",
    returnPolicy: "7 days easy return",
    lastRestocked: new Date("2024-01-18"),
  },
  {
    id: "4",
    sku: "JL-CK-004",
    name: "Contemporary Kurti Set",
    price: 3999,
    originalPrice: 4999,
    discount: 20,
    cost: 2200,
    image: "/placeholder.svg?height=500&width=400&text=Kurti+Set",
    images: [
      "/placeholder.svg?height=500&width=400&text=Kurti+Set+1",
      "/placeholder.svg?height=500&width=400&text=Kurti+Set+2",
    ],
    category: "kurtis",
    description: "Modern kurti with palazzo pants, perfect for casual and office wear. Features comfortable fabric, stylish cut, and versatile design suitable for daily wear.",
    colors: ["Cream", "Dusty Rose", "Gold Taupe"],
    sizes: ["XS", "S", "M", "L", "XL"],
    material: "Cotton Blend",
    care: ["Machine wash", "Tumble dry low", "Iron if needed"],
    features: ["Comfortable Fit", "2-Piece Set", "Casual Wear", "Easy Care", "Office Wear"],
    rating: 4.4,
    reviews: 203,
    isNew: true,
    isBestseller: false,
    inStock: true,
    stockCount: 35,
    stockAlert: 12,
    vendor: "Daily Wear Essentials",
    weight: 0.6,
    dimensions: { length: 2.8, width: 1.4, height: 0.1 },
    tags: ["kurti", "casual", "office-wear", "cotton", "comfortable"],
    condition: "new",
    warranty: "Fabric quality guarantee",
    returnPolicy: "15 days hassle-free return",
    lastRestocked: new Date("2024-01-22"),
  },
  {
    id: "5",
    sku: "JL-FS-005",
    name: "Festive Silk Saree",
    price: 7999,
    originalPrice: 9999,
    discount: 20,
    cost: 4800,
    image: "/placeholder.svg?height=500&width=400&text=Festive+Silk+Saree",
    category: "sarees",
    description: "Beautiful silk saree perfect for festivals and celebrations. Features traditional motifs and rich colors that embody the spirit of Indian festivities.",
    colors: ["Burgundy", "Golden", "Forest Green"],
    sizes: ["Free Size"],
    material: "Art Silk",
    rating: 4.5,
    reviews: 78,
    isNew: false,
    isBestseller: true,
    inStock: true,
    stockCount: 18,
    stockAlert: 6,
    vendor: "Festival Collection",
    weight: 0.7,
    tags: ["silk", "festive", "traditional", "celebration"],
    condition: "new",
    lastRestocked: new Date("2024-01-16"),
  },
  {
    id: "6",
    sku: "JL-PL-006",
    name: "Party Wear Lehenga",
    price: 15999,
    originalPrice: 19999,
    discount: 20,
    cost: 11000,
    image: "/placeholder.svg?height=500&width=400&text=Party+Lehenga",
    category: "lehengas",
    description: "Glamorous party wear lehenga with modern design elements. Perfect for cocktail parties, receptions, and special evening events.",
    colors: ["Dusty Rose", "Charcoal", "Gold Taupe"],
    sizes: ["S", "M", "L", "XL"],
    material: "Net & Satin",
    rating: 4.7,
    reviews: 92,
    isNew: true,
    isBestseller: false,
    inStock: true,
    stockCount: 12,
    stockAlert: 4,
    vendor: "Party Perfect",
    weight: 1.8,
    tags: ["party-wear", "modern", "glamorous", "evening"],
    condition: "new",
    lastRestocked: new Date("2024-01-21"),
  },
  {
    id: "7",
    sku: "JL-SS-007",
    name: "Traditional Sharara Set",
    price: 11999,
    originalPrice: 14999,
    discount: 20,
    cost: 7500,
    image: "/placeholder.svg?height=500&width=400&text=Sharara+Set",
    category: "suits",
    description: "Classic sharara set with traditional embroidery and modern cut. Features authentic craftsmanship with contemporary styling.",
    colors: ["Cream", "Burgundy", "Forest Green"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    material: "Silk & Chiffon",
    rating: 4.6,
    reviews: 67,
    isNew: false,
    isBestseller: false,
    inStock: true,
    stockCount: 14,
    stockAlert: 5,
    vendor: "Traditional Crafts",
    weight: 1.4,
    tags: ["sharara", "traditional", "embroidery", "festive"],
    condition: "new",
    lastRestocked: new Date("2024-01-17"),
  },
  {
    id: "8",
    sku: "JL-CK-008",
    name: "Printed Cotton Kurti",
    price: 2499,
    originalPrice: 2999,
    discount: 17,
    cost: 1400,
    image: "/placeholder.svg?height=500&width=400&text=Cotton+Kurti",
    category: "kurtis",
    description: "Comfortable printed cotton kurti for everyday wear. Features breathable fabric and stylish prints perfect for casual occasions.",
    colors: ["Cream", "Dusty Rose", "Gold Taupe", "Forest Green"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    material: "Pure Cotton",
    rating: 4.3,
    reviews: 145,
    isNew: true,
    isBestseller: false,
    inStock: true,
    stockCount: 28,
    stockAlert: 10,
    vendor: "Cotton Craft Co.",
    weight: 0.4,
    tags: ["cotton", "printed", "casual", "everyday"],
    condition: "new",
    lastRestocked: new Date("2024-01-23"),
  },
]

export const testimonials = [
  {
    id: 1,
    name: "Priya Sharma",
    location: "Mumbai",
    rating: 5,
    comment: "Absolutely stunning sarees! The quality is exceptional and the designs are breathtaking. I've received countless compliments. The fabric feels premium and the colors are vibrant. Highly recommended!",
    image: "/placeholder.svg?height=80&width=80&text=Priya",
  },
  {
    id: 2,
    name: "Anita Patel",
    location: "Delhi",
    rating: 5,
    comment: "Beautiful collection and excellent customer service. My bridal lehenga was perfect for my special day! The intricate work and attention to detail was remarkable. Thank you for making my wedding memorable!",
    image: "/placeholder.svg?height=80&width=80&text=Anita",
  },
  {
    id: 3,
    name: "Meera Reddy",
    location: "Bangalore",
    rating: 5,
    comment: "Love the elegant designs and premium quality. Jai Laxmi Sarees is my go-to for ethnic wear! Every piece I've bought has exceeded my expectations. The craftsmanship is truly authentic.",
    image: "/placeholder.svg?height=80&width=80&text=Meera",
  },
]

// Sample stock entries for demonstration
export const sampleStockEntries: StockEntry[] = [
  {
    id: "stock-001",
    productId: "1",
    type: "purchase",
    quantity: 20,
    previousStock: 10,
    newStock: 30,
    reason: "New inventory purchase",
    reference: "PO-2024-001",
    timestamp: new Date("2024-01-15T10:00:00Z"),
    userId: "admin-001",
    notes: "Received fresh stock from Banarasi Silk Weavers Co-op"
  },
  {
    id: "stock-002",
    productId: "1",
    type: "sale",
    quantity: -15,
    previousStock: 30,
    newStock: 15,
    reason: "Product sales",
    reference: "SALES-BATCH-001",
    timestamp: new Date("2024-01-20T15:30:00Z"),
    notes: "High demand during festival season"
  },
]

// Sample stock alerts
export const sampleStockAlerts: StockAlert[] = [
  {
    id: "alert-001",
    productId: "2",
    productName: "Designer Bridal Lehenga",
    currentStock: 8,
    alertLevel: 10,
    severity: "low",
    created: new Date("2024-01-21T09:00:00Z"),
    acknowledged: false,
  },
  {
    id: "alert-002",
    productId: "6",
    productName: "Party Wear Lehenga",
    currentStock: 4,
    alertLevel: 5,
    severity: "critical",
    created: new Date("2024-01-22T14:20:00Z"),
    acknowledged: false,
  },
]
